In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [4]:
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [5]:
type(my_array)

numpy.ndarray

In [6]:
# within array has to be same data type
list2=[6,7,8,9,10]
myarray=np.array(my_list,list2)

TypeError: Field elements must be 2- or 3-tuples, got '6'

In [9]:
list2=[6,7,8,9,10]
myarray=np.array([my_list,list2])
myarray
# note has to have []

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
myarray.shape

(2, 5)

In [12]:
myarray.size

10

In [13]:
myarray.dtype

dtype('int64')

In [16]:
a=np.identity(n=5) # create 5 by 5 with 1 cross
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
a.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [19]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
myarray.ravel('f') # order C for row f for columns

array([ 1,  6,  2,  7,  3,  8,  4,  9,  5, 10])

In [28]:
myarray.flatten() # to 1 lower demention

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
myarray.T #change colum to row; row to columns

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [33]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
np.flipud(myarray) # flip up side down

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [38]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
np.fliplr(myarray) # flip left to right not inplace no alter origin

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [41]:
np.rot90(myarray,k=1) # rotation clockwise, k mean how many times perform rotation

array([[ 5, 10],
       [ 4,  9],
       [ 3,  8],
       [ 2,  7],
       [ 1,  6]])

In [42]:
one_d_array=np.array([1,2,3,4,5,6])

In [43]:
# Create a new 2d array
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12]) # u can use +6 on array but not on list
two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [58]:
# concatenate 2 arrays
newarray=np.array([[10,20,30],[40,50,60],[70,80,90]])
np.concatenate((two_d_array,newarray),axis=1) # 1 is on row and to right # 0 not working cuz one array has 6 colunms the other only have 3

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

Math apply on array is elements wise

In [60]:
two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [61]:
two_d_array+1 # note here we can apply math without a for loops

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [62]:
two_d_array*2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36]])

In [63]:
two_d_array%2

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [64]:
# same demetional array can add substract to eachother elemental wise
neww=np.array([[1,2],[3,4]])
neww+neww # each number add to it self both on its index position

array([[2, 4],
       [6, 8]])

In [65]:
neww**neww

array([[  1,   4],
       [ 27, 256]])

In [67]:
np.mean(two_d_array) # average of all element of array even it is two dementional

9.5

In [68]:
two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [70]:
np.mean(two_d_array,axis=1) # it give the mean for each row axis=1 mean cross each row

array([ 3.5,  9.5, 15.5])

In [71]:
np.sum(two_d_array,axis=0)

array([21, 24, 27, 30, 33, 36])